version: '3'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    command: yarn backend
    environment:
      - NODE_ENV=production

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    command: yarn client
