export const SET_MENU = '@customization/SET_MENU'
export const MENU_OPEN = '@customization/MENU_OPEN'
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY'
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS'
export const SET_THEME = '@customization/SET_THEME'
export const GET_JIRA = '@data/GET_JIRA'
export const GET_UNIT = '@data/GET_UNIT'
export const GET_E2E = '@data/GET_E2E'
