name: Deploy Frontend to GitHub Pages

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  persist-credentials: false

            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install Dependencies
              run: cd packages/client && yarn install

            - name: Build Frontend
              run: cd packages/client && yarn build

            - name: Deploy Frontend
              uses: JamesIves/github-pages-deploy-action@4.1.3
              with:
                  branch: gh-pages
                  folder: build
                  token: ${{ secrets.GITHUB_TOKEN }}
